default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  database: erb_test_development

test:
  <<: *default
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  database: erb_test_test

production:
  <<: *default
  host: ec2-54-243-228-140.compute-1.amazonaws.com
  database: d2s55v5h2i6iq4
  username: veelhmajgbpbgi
  password: 0c13df90831cbc23b2746c98e3f3516d19b292177c1601950ca4c10dfeecd487
  port: 5432
  url: postgres://veelhmajgbpbgi:0c13df90831cbc23b2746c98e3f3516d19b292177c1601950ca4c10dfeecd487@ec2-54-243-228-140.compute-1.amazonaws.com:5432/d2s55v5h2i6iq4

