default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: erb_test_development

test:
  <<: *default
  database: erb_test_test

production:
  <<: *default
  database: erb_test_production
